-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgjSPWRqshVqFrDks9+ALrvykOSxiu8ck+XfJmtaqDM66gCgYIKoZIzj0DAQehRANCAATgwEz04m/o/JAAQNwcVX6hjrjaWDX+nrIbcH4GzbW8feFJ4KmTBQWkeFrMt4ihLLbIm7HyE3oAkNlURkdaZgCn
-----END PRIVATE KEY-----